### ISSUE TITLE
CMake requires Python developer files

### ISSUE THREAD

**Issue by martin-ueding** [JeffersonLab/qphix-codegen#6]
Bartek tried the CMake version and it could not find Python 3 on his Linux Mint machine. The package `python3-dev` was missing. On my Fedora machine I have `python3-devel` installed, so that is not an issue.

I would think that we only need the Python 3 interpreter, so the line that searches for the libraries is not really needed and makes it harder for users to satisfy those dependencies.

**Comment by bjoo** [comment]
Yes, we would need to bulletproof this more in the CMakeLists (like your original generate-and-compile.sh script did). I have a custom Python3 + Jinja2  install, as networking from my build node is restricted.
So I had to expliclitly put Python3 and its shared libs on my PATH and LD_LIBRARY_PATH. Then things worked for me, but if this is not set up in the shell, things will go haywire.

Best, 
 B
> On Jun 14, 2017, at 11:42 AM, Martin Ueding <notifications@github.com> wrote:
> 
> Bartek tried the CMake version and it could not find Python 3 on his Linux Mint machine. The package python3-dev was missing. On my Fedora machine I have python3-devel installed, so that is not an issue.
> 
> I would think that we only need the Python 3 interpreter, so the line that searches for the libraries is not really needed and makes it harder for users to satisfy those dependencies.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--------------------------------------------------------------------------------------
Dr Balint Joo              High Performance Computational Scientist
Jefferson Lab
12000 Jefferson Ave, Suite 3, MS 12B2, Room F217,
Newport News, VA 23606, USA
Tel: +1-757-269-5339,      Fax: +1-757-269-5427
email: bjoo@jlab.org       
-------------------------------------------------------------------------------------
