### ISSUE TITLE
Output directories are not created

### ISSUE THREAD

**Issue by martin-ueding** [JeffersonLab/qphix-codegen#7]
It seems that the output directories are not created. If they don't exist, the codegen does not fail, it just does not creates anything. Then subsequent parts of the build fail because the files do not exist.

**Comment by bjoo** [comment]
OK. I can fix that in qphix-codegen if you don’t get to it first. I’ll be able to look at it again in about 1 hour from now.

> On Jun 16, 2017, at 2:59 PM, Martin Ueding <notifications@github.com> wrote:
> 
> It seems that the output directories are not created. If they don't exist, the codegen does not fail, it just does not creates anything. Then subsequent parts of the build fail because the files do not exist.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--------------------------------------------------------------------------------------
Dr Balint Joo              High Performance Computational Scientist
Jefferson Lab
12000 Jefferson Ave, Suite 3, MS 12B2, Room F217,
Newport News, VA 23606, USA
Tel: +1-757-269-5339,      Fax: +1-757-269-5427
email: bjoo@jlab.org       
-------------------------------------------------------------------------------------
